version: '3'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  postgres:
    image: postgres:13.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - postgres_network

  web:
    image: serg733/yamdb_final_web:v1.0
    restart: always
    volumes:
      - static_volume:/code/static  # <-- bind the static volume
      - media_volume:/code/media  # <-- bind the media volume
    depends_on:
      - postgres
    env_file:
      - ./.env
    networks:
      - nginx_network
      - postgres_network

  nginx:
    image: nginx:1.19.6
    ports:
      - 8000:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/code/static
      - ./media:/code/media
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  postgres_network:
    driver: bridge
