version: '3'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:13.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: serg733/yamdb_final_web:latest
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.6
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./www/yamdb_final/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www/yamdb_final/static:/code/static
      - ./www/yamdb_final/media:/code/media
    depends_on:
      - web
