version: '3'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:13.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: serg733/yamdb_final_web:latest
    restart: always
    volumes:
      - ./static:/code/static  # <-- bind the static volume
      - ./media:/code/media  # <-- bind the media volume
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.6
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/default.conf
      - ./static:/code/static
      - ./media:/code/media
    depends_on:
      - web
